ARG BASE_IMAGE_VERSION
ARG ZFS_VERSION
ARG PARENT_IMAGE=quay.io/fedora/fedora-coreos:$BASE_IMAGE_VERSION

FROM quay.io/fedora/fedora-coreos:$BASE_IMAGE_VERSION AS kernel-version

# Builds ZFS
RUN rpm --query --all --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}' kernel >/var/kernel.version

FROM registry.fedoraproject.org/fedora:${BASE_IMAGE_VERSION%%.*} AS builder
ARG BASE_IMAGE_VERSION
ARG ZFS_VERSION

COPY --from=kernel-version /var/kernel.version /root/
# https://openzfs.github.io/openzfs-docs/Developer%20Resources/Custom%20Packages.html
# https://openzfs.github.io/openzfs-docs/Developer%20Resources/Building%20ZFS.html
RUN curl "https://src.fedoraproject.org/rpms/fedora-repos/raw/f${BASE_IMAGE_VERSION%%.*}/f/fedora-updates-archive.repo" --output-dir /etc/yum.repos.d --remote-name --remote-time \
  && dnf -y install \
    autoconf \
    automake \
    dkms \
    gcc \
    jq \
    "kernel-devel-$(cat /root/kernel.version)" \
    kernel-rpm-macros \
    libaio-devel \
    libattr-devel \
    libblkid-devel \
    libffi-devel \
    libtirpc-devel \
    libtool \
    libunwind-devel \
    libuuid-devel \
    make \
    ncompress \
    openssl \
    openssl-devel \
    python3 \
    python3-cffi \
    python3-devel \
    python3-packaging \
    python3-setuptools \
    rpm-build \
    systemd \
    systemd-devel \
    zlib-ng-compat-devel \
  && curl "https://github.com/openzfs/zfs/releases/download/zfs-$ZFS_VERSION/zfs-$ZFS_VERSION.tar.gz" --location --output-dir /root --remote-name --remote-time \
  && tar --extract --file /root/zfs-*.tar.gz --gzip --directory /root \
  && rm --verbose /root/zfs-*.tar.gz \
  && pushd /root/zfs-* \
  && ./configure -with-linux="/usr/src/kernels/$(cat /root/kernel.version)/" -with-linux-obj="/usr/src/kernels/$(cat /root/kernel.version)/" \
  && make -j "$(nproc)" rpm-utils rpm-kmod \
  && popd \
  && dnf clean all \
  && ls -Al /root/zfs-*/*.rpm

# Install ZSF
FROM $PARENT_IMAGE
COPY --from=builder /root/zfs-*/*.rpm /root/
RUN rm --verbose --force \
    /root/zfs-test-*.rpm \
    /root/*.src.rpm \
    /root/*-debugsource-*.rpm \
    /root/*-debuginfo-*.rpm \
    /root/*-devel-*.rpm \
  && rpm-ostree install -y /root/*.rpm \
  && rm --verbose /root/*.rpm \
  && depmod -a "$(rpm --query --all --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}' kernel)" \
  && printf 'zfs\n' >/etc/modules-load.d/zfs.conf \
  && rm --recursive \
    /var/cache \
    /var/lib/pcp \
    /var/log 

# Install additional software
RUN rpm-ostree install -y \
    zsh \
    atuin \
    podman-compose

RUN rm --recursive /var/cache 

RUN ostree container commit